// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRz9LdhhY_PK5J8NIamnWgtryeoG_l7oQ',
    appId: '1:351438376127:web:fc8606df55c789464d4a0a',
    messagingSenderId: '351438376127',
    projectId: 'pet-adoption-b9afe',
    authDomain: 'pet-adoption-b9afe.firebaseapp.com',
    storageBucket: 'pet-adoption-b9afe.firebasestorage.app',
    measurementId: 'G-CRG1RPZSL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACgChEkJBcdyZNHNmCjfvVJHrGHWqA7GI',
    appId: '1:351438376127:android:197decede23f0aa64d4a0a',
    messagingSenderId: '351438376127',
    projectId: 'pet-adoption-b9afe',
    storageBucket: 'pet-adoption-b9afe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbgjUvTpqJ1F4Sy0q607cbZH9r-n0d0r8',
    appId: '1:351438376127:ios:9d94b59fb0a5ce6d4d4a0a',
    messagingSenderId: '351438376127',
    projectId: 'pet-adoption-b9afe',
    storageBucket: 'pet-adoption-b9afe.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbgjUvTpqJ1F4Sy0q607cbZH9r-n0d0r8',
    appId: '1:351438376127:ios:9d94b59fb0a5ce6d4d4a0a',
    messagingSenderId: '351438376127',
    projectId: 'pet-adoption-b9afe',
    storageBucket: 'pet-adoption-b9afe.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRz9LdhhY_PK5J8NIamnWgtryeoG_l7oQ',
    appId: '1:351438376127:web:5c20e62bfbe8c8dc4d4a0a',
    messagingSenderId: '351438376127',
    projectId: 'pet-adoption-b9afe',
    authDomain: 'pet-adoption-b9afe.firebaseapp.com',
    storageBucket: 'pet-adoption-b9afe.firebasestorage.app',
    measurementId: 'G-WMEQPFPJ24',
  );
}
